### PR TITLE
font: Allow adding font to the config. In prep for border titles

### PR DESCRIPTION
**Pull request by crondog**

### CODE REVIEW

**Comment by SirCmpwn** [comment]
The bar font should use this if the user doesn't specify one.

**Comment by SirCmpwn** [comment]
Needs a default value too.

**Comment by crondog** [comment]
Sure

**Comment by SirCmpwn** [comment]
Thanks!

**Comment by ke7ofi** [comment]
What's the default?

**Comment by crondog** [comment]
It's in the code

**Pull request merged**
