### PR TITLE
Set the arch release based on dynamic date output

### PR DESCRIPTION
**Pull request by solarce**
Related to a support request we, Travis CI, got. This should fix your current build setup.

### CODE REVIEW

**Comment by SirCmpwn** [comment]
Thanks! I also followed up on email, but may as well ask this here. It looks like your builds are running on the legacy infrastructure, where as suddenly my builds were running on the new infrastructure (which led me to believe that it was this Travis change that caused failures). Will this change fix builds on the new Travis infrastructure?

**Comment by mikkeloscar** [comment]
This is an arch-travis issue. I have fixed it here: mikkeloscar/arch-travis@c07c52e.

However I'm not sure this is related to the other problems seen on the new Travis infrastructure, but it clashed because the iso was updated today.

@solarce as an example this was build on the new infrastructure and failed, but not because of the `ARCH_ISO` value.

**Comment by solarce** [comment]
@mikkeloscar great, the other error is due to a change in the UID of the `travis` user on our GCE images, because of the presence of a default `ubuntu` user. 

https://github.com/solarce/arch-travis/commit/675009ce736a621cdda254082721ebac9880d837 is a work-around until we get new GCE images made with the ubuntu user removed.

**Comment by mikkeloscar** [comment]
@solarce I'll merge it if you make a PR of that fix, It doesn't seem like it will cause problems even when the ubuntu user is removed at some point.

**Comment by solarce** [comment]
Happy to! https://github.com/mikkeloscar/arch-travis/pull/4

**Comment by mikkeloscar** [comment]
@SirCmpwn the issue this PR solves and the other issue related to running arch-travis on GCE (as discussed above) should be resolved now in arch-travis.

**Comment by SirCmpwn** [comment]
So this PR is now obsolete?

**Comment by mikkeloscar** [comment]
Yes, next time sway is build on travis these changes will take effect.

**Pull request closed without merging**
