### PR TITLE
Implement sort_workspaces() function for outputs.

### PR DESCRIPTION
**Pull request by zandrmartin**
This seems to have resolved issue #669 for me. Please give it a careful review, it's getting pretty heavy into C for my current comfort level and may have side effects I am not aware of.

### CODE REVIEW

**Comment by progandy** [comment]
Are you sure this is right? I think that workspaces without numbers should not be sorted.

**Comment by zandrmartin** [comment]
SirCmpwn asked about this in IRC and was going to review this PR. It is a change; whether it's one people want is the question. I'm open to removing the alphabetic sorting portion of it. I only use numbered workspaces so it makes no difference to me.

Based on what I can tell from looking at the i3 source, it appears i3 does not sort alphabetically. So alphabetic sorting should not be included if duplicating i3's behavior is the goal. Personally, I like things to be sorted. :smile:

**Comment by SirCmpwn** [comment]
Alright, verdict: implement the i3 behavior by default, but add a config command if you'd like both options.

**Comment by SirCmpwn** [comment]
Is qsort stable?

**Comment by zandrmartin** [comment]
I'll remove the alphabetic sorting for now, though adding it as an option with a config command might be a fun little project.

@SirCmpwn I do not understand your question "is qsort stable?"

**Comment by SirCmpwn** [comment]
A stable sort, I mean. Does it retain the sort order of equivalent items?

**Comment by zandrmartin** [comment]
Ah! Yes, it is. I removed the alphabetic sorting and did some testing. The tests involved setting up ad hoc workspaces on each monitor, then turning off the right monitor and seeing how they ended up on the left. Results:

    Left: 000
    Right: 00, 0
    Final: 000, 00, 0

    Left: 1, def
    Right: abc
    Final: 1, def, abc

    Left: 1, 13
    Right: 12
    Final: 1, 12, 13

    Left: "2: ZZZ"
    Right: "2: AAA"
    Final: "2: ZZZ", "2: AAA"

So I think this is sorting as expected.

**Comment by SirCmpwn** [comment]
Cool. Will merge once that change lands in this PR.

**Comment by SirCmpwn** [comment]
And the build passes.

**Comment by progandy** [comment]
qsort is not stable, it doesn't guarantee the order. [1] AFAIK glibc is using a stable mergesort, but that isn't guaranteed.
There are ways to make it stable, e.g. by adding an order field to the workspace structure.

[1] http://www.gnu.org/software/libc/manual/html_node/Array-Sort-Function.html
[2] http://nullprogram.com/blog/2014/08/29/

**Comment by zandrmartin** [comment]
I'm sorry, I didn't realize @SirCmpwn was asking about the `qsort` function itself. I thought he was asking whether my cmp function that is passed to `qsort` returned 0 for equivalent items. Apparently there is no guaranteed-stable sorting function in stdlib (https://rosettacode.org/wiki/Sort_stability#C).

I'm open to any option here:
- revert this entirely - at this point `sort_workspaces` is being used in a couple places though, so that will require some unwinding of other changes
- add an order field to `swayc_t` to use for `qsort`ing workspaces (might be handy for other container types too?)
- write a custom function to sort workspaces that doesn't use `qsort` at all (this might be above my current skill level but I would give it a try)
- leave it - I personally don't think this matters too much but as mentioned above, I only use numbered workspaces and don't have `workspace prev|next` bound to anything

I apologize for the trouble here, I should've understood the situation better before trying to fix it. :confused:

**Comment by SirCmpwn** [comment]
Let's add a qsort_stable to stringop.c.

**Pull request merged**
