### PR TITLE
Make it possible to move views between outputs

### PR DESCRIPTION
**Pull request by mikkeloscar**
This patch makes it possible to move views between outputs using the
`move left|right|up|down` commands.

It behaves similar to i3 with one important difference. The focus will
always follow the view being moved, unlike i3 where the focus doesn't
always follow the view to a new output (I assume that's a bug in i3).

### CODE REVIEW

**Comment by SirCmpwn** [comment]
Paging @stapelberg to confirm that assumption.

**Comment by stapelberg** [comment]
I’m assuming “view” in sway maps to “container” in i3.

The idea behind not moving focus to the destination output is that it caters better to the use-case where you want to bulk-redistribute a couple of windows from one output/workspace. Imagine you just accumulate windows over time and then decided to clean them up and put them on proper workspaces. Focus staying on the source workspace means that you don’t need to switch back and forth between workspaces/outputs. For people who prefer focus to allows follow the window, they can adjust the keybinding(s) from `move to output <foo>` to `move to output <foo>, focus`.

**Comment by SirCmpwn** [comment]
Seems reasonable to me. Let's go with that behavior.

>I’m assuming “view” in sway maps to “container” in i3.

Indeed, but specifically refers to a window as opposed to any kind of container.

**Comment by mikkeloscar** [comment]
@stapelberg Thanks for describing why it works that way.

> For people who prefer focus to allows follow the window, they can adjust the keybinding(s) from move to output <foo> to move to output <foo>, focus.

How do you do this for a command like `move left`, so the focus follows the window which is moved to the output at the left of the current one?

The situation you describe sounds like it would better handled by `move container/window to workspace/output <foo>` because then you can not only send the windows to another visible workspace but you can send it to any number of workspaces.

**Comment by stapelberg** [comment]
> How do you do this for a command like move left, so the focus follows the window which is moved to the output at the left of the current one?

You use `move left, focus`. Due to using the comma, both commands will be applied to the same window.

**Comment by mikkeloscar** [comment]
Ok, this is gonna sound strange.

When I logged into i3 today to test this behavior I was able to move windows from output to output with just `move left|right|up|down` and have the focus follow the window, like expected. I'm certain this didn't work the other night when I tested it for this patch, so I'm a bit confused as to what is the right behavior. It seems to me that i3 was in some weird state the other day when I tested it, such that it didn't work. So now I really do assume it's a bug in i3, unless there is some state where this behavior is expected, which I can't think of.

I will try to see if I can trigger this assumed bug again to confirm.

**Comment by mikkeloscar** [comment]
Ok, now I'm pretty certain this is a bug in i3.
After doing work for about 3 hours (since my previous comment) `move left|right|up|down` has stopped working as I would expect, e.g. focus doesn't follow the window to a new output.
I still don't know when the bug was triggered, but simply running the i3 command `restart` fixed the problem, so i3 must end up in some state where it doesn't work, which is corrected by restarting i3 with the exact same window/workspace layout as when it didn't work before the restart.

@stapelberg I will try to gather a bit more info about this and eventually open an issue for i3.

@SirCmpwn What do you think, have I made my case that this PR does the right thing? :)

**Comment by SirCmpwn** [comment]
It's not sway's place to change i3's behavior. I'll merge it as-is if @stapelberg agrees that it's a bug.

**Comment by SirCmpwn** [comment]
Status of this?

**Comment by mikkeloscar** [comment]
@SirCmpwn I opened an issue regarding at i3/i3#2257. It has been marked as a **bug** so I guess it's a confirmed bug in i3 now.

**Comment by SirCmpwn** [comment]
Have you updated your pull request to implement the *desired* behavior of i3, rather than the behavior originally presented by this PR?

**Comment by mikkeloscar** [comment]
Ok, this thread has become a bit confusing, let me *try* to clear it up.

I have NOT changed the original behavior of the PR because I believe it implements the *desired* behavior of i3.

The reason I believe this is that when I launch i3 it behaves the same as this PR, but after the bug occur (as described in i3/i3#2257), it behaves like @stapelberg suggested.
I think @stapelberg was confusing the behavior of `move container/window to workspace/output <foo>` and `move left|right|up|down` because he wasn't initially aware of the bug (Michael, please correct me if I'm making a wrong assumption here).

Also, i3/i3#2257 includes this:

> **What I expected instead:**
>
> I expect the commands move left|right|up|down to always maintain focus when moving a window > between outputs.

and since it has been marked as bug, I assume this expected behavior has been confirmed.

**Comment by SirCmpwn** [comment]
@Airblader added the bug tag on the i3 issue, let's bring him in. I'm still not convinced that the original PR behavior is the desired i3 behavior, I'd like to hear it from the horse's mouth.

**Comment by Airblader** [comment]
The bug tag only refers to what type of issue it is. It does not do all imply that it's reproducible or that we do consider it wrong behavior. I add the bug tag to all issues that don't get the enhancement tag. :)

**Comment by SirCmpwn** [comment]
Status of this?

**Comment by stapelberg** [comment]
Please see https://github.com/i3/i3/issues/2257#issuecomment-210334756

**Comment by SirCmpwn** [comment]
Thanks for clarifying, @stapelberg.

**Comment by SirCmpwn** [comment]
Bump. What's the status of this? I'm okay with the original pitch (after @acrisci's comment), but I want to have it synced up with master and a quick sanity check to make sure it still works.

**Comment by acrisci** [comment]
My vote is to keep it how it works now, to have the same behavior moving between outputs as on the same output.

**Comment by mikkeloscar** [comment]
@SirCmpwn I'm sorry I haven't been active lately. I was away last week, and for this whole week I have been (and still is) quite sick with fever :(

To top it off, next week I start a new job in a another country, so I will be quite busy with that for a while as well.

So unfortunately I don't know when I will get around to fixing this up.
It's fine by me if you wanna close it, then I can just reopen when I get time to fix it.

**Comment by SirCmpwn** [comment]
It's all good, @mikkeloscar. I'll see if I can tidy it up and get it merged myself when I have time.

**Comment by acrisci** [comment]
This is a feature I use a lot in i3 so I would like to see this in sway. I can take this up if nobody is working on it.

**Comment by SirCmpwn** [comment]
Open a new pull request tidying it up and fixing the merge conflicts if you want it in sooner rather than later.

**Comment by mikkeloscar** [comment]
@acrisci just rebased on master, last I worked on this it worked fine, but there was some movements on a single monitor that I wanted to fix before it was merged. I don't know if it still works, but please have a look if you have time, unfortunately I don't have much time these days.

**Comment by acrisci** [comment]
Thanks.

I looked more closely and I'm seeing a lot of misses for how sway handles some subtle cases for movement that I use occasionally, so I think I'm going to have to do more work to get it right.

By the way, it would be very beneficial to have tests for this at some point.

**Comment by SirCmpwn** [comment]
Tests have been looked into. I wasn't satisfied with any of the available testing frameworks for C.

**Comment by stapelberg** [comment]
> I wasn't satisfied with any of the available testing frameworks for C.

Which features were you missing, specifically?

Have you considered implementing a blackbox test framework in a language other than C? As you might be aware of, i3 has a Perl test suite which I consider successful — certainly it has provided a lot of confidence for accepting contributions more quickly and doing larger refactorings. I consider having a comprehensive test suite vital for a FOSS project at a certain size, and the sooner it’s started, the easier it is to implement :).

**Comment by SirCmpwn** [comment]
I've done *lots* of research, including into the i3 tests. I'm sure they work well for you, but they aren't the sort of thing I'm looking for. There have been some discussions about a third party running the actual i3 test suite against sway, which I would love to see happen, but as far as upstream testing is concerned I'd like to identify something better.

I recently wrote a blog post that talks about the usefulness of mocking and includes an example of what a test using my ideal test framework would look like, to give some extra details: https://drewdevault.com/2016/07/19/Using-Wl-wrap-for-mocking-in-C.html

Tests are something that's talked about a lot in the sway community and I definitely want to have them, but I don't think any of the solutions I've seen or researched so far are as effective as I would like.

**Comment by stapelberg** [comment]
I’m going to avoid getting into a debate about the merits of mocking, but let me give you two pieces of well-meant advice before becoming a lurker again:

1. Perfect is the enemy of the good. i3’s tests aren’t the pinnacle of elegance either, but nevertheless they have helped a lot.
2. If you are dead set on this approach and on doing it on your own, I’d recommend to drop everything else and implement the test suite right away. A test suite will pay for itself very quickly.

**Comment by SirCmpwn** [comment]
I definitely understand the value of a test suite, though I don't think it's drop-everything-and-do-it-now valuable. Sway is still shipping 0.x releases, and I'm okay with some buginess (and actually sway has got a surprisingly small number of bugs all things considered). As I said earlier, I would be thrilled if a third party started setting up tests out of tree, and I might even contribute to them, but I don't want to start shipping a test suite upstream until I find or build a solution that I'm satisfied with. In my opinion the best way to test is to consider each tested function a contract and use mocking to test its obedience to that contract in isolation, plus tests more along the lines of what i3 uses to make sure all of the individually-tested pieces work together correctly (integration tests). I don't want to throw away a bunch of work when the right solution *does* come along.

For the record there's a branch where I started implementing a test suite based on cmocka, which I thought was the closest available test framework to what I'm looking for, but I abandoned the branch because of complications with how cmocka is implemented. The branch is here: https://gogs.sr.ht/SirCmpwn/sway

**Comment by Airblader** [comment]
One bug problem with waiting is that you'll never get anyone contributing tests alone. Starting early with tests is the only way, imho, to have the application well-tested later on. It admittedly slows development initially but I agree with Michael, it pays out quite quickly. Especially when that 1.0 release comes rolling around.

**Comment by SirCmpwn** [comment]
The cmocka tests were *so close*, but it fell apart as I tried to make it work for more complex parts of sway. I was going to try and improve cmocka to meet our needs but the codebase is pretty gross. I'd be better off just writing a new test framework, so I'll be looking into that in the nearish future. It's one of the things I would like to do prior to shipping 1.0. Believe me, I completely understand the value of a test suite, as well as the difficulty in introducing one late in development, but this is what I think is best.

I've said before that I will give due consideration to any pull request proposed that adds a test suite, by the way. If someone else thinks they have a strategy that will do the trick, then by all means give it a shot and open up a PR. It doesn't even need to be perfect, I just need to feel like it will scale to the entire codebase and still be effective.

**Comment by acrisci** [comment]
Let me also add that you should strongly consider how easy it is for new contributors to write tests in your assessment of any testing framework. The i3 test suite is a big barrier of entry to new contributors because perl literacy is low among new developers and it has a large number of dependencies that are tricky to install (unless you are a perl guru).

You should also consider how fun it is to write tests. As a community project, almost all of your users are contributing code just for fun and only for their own personal use. If they encounter a test framework that is too difficult or feels too much like what they have to do at their day job, they will be more likely to keep personal forks rather than write tests.

All around, the i3 test suite does both of these very well (despite perl). Tests are conceptually very easy to understand because they are exactly like what you would do manually to test the bug or feature. That means there is no extra planning needed to design tests. From my experience, they can also be very fun to write.

**Comment by SirCmpwn** [comment]
Replaced by #500

**Pull request closed without merging**
