### PR TITLE
Basic Zsh auto-completion for --options

### PR DESCRIPTION
**Pull request by SethBarberee**
Hi, I've created at least a skeleton of zsh completion files for the sway, swaymsg, and swaygrab. Currently, it is only for --options but I will work on the other commands unless you say otherwise.
I'm sorry if it is a mess because it is my first time submitting a pull request to anything.

### CODE REVIEW

**Comment by mikkeloscar** [comment]
I think this is good, but maybe rename the files to something like `completion.zsh` or `swaymsg-completion.zsh` etc.

Also please use tabs for indentation, right now you use a mix of tabs and spaces :)

**Comment by SethBarberee** [comment]
I'll make sure to do that. The only thing that isn't in my request but should be is an update to cmake to install those files to the appropriate directory for zsh completions. I didn't do that because I did not how to code cmake.

**Comment by mikkeloscar** [comment]
It's pretty much done like this: https://github.com/SirCmpwn/sway/blob/master/CMakeLists.txt#L121

**Comment by SethBarberee** [comment]
Could this work for the cmake file? They will be placed with this cmake file in a directory called completions. However, the problem with suffixing them with .zsh screws up the autoloading feature because it has to be prefixed with an underscore such as _(command) for each completion file. If I am wrong, then please tell me!
https://gist.github.com/SethBarberee/7c833c963d06d1f4c778

**Comment by SirCmpwn** [comment]
That should work. Make it optional, though.

**Comment by crondog** [comment]
Shouldn't the directory be `share/zsh/site-functions` as that is where third party completions go

**Comment by SethBarberee** [comment]
I debated this on the sway IRC was told that it was share/zsh/Completions/ but I do agree with you, crondog. I too think it should be share/zsh/site-functions.

**Comment by mikkeloscar** [comment]
@SethBarberee `share/zsh/site-functions` is the correct path as mentioned by @crondog.

Could you also move the files to `completions/zsh` then it will be possible to add bash completions if anyone want that at some point.

Other than that it looks good.

**Comment by SethBarberee** [comment]
Will do :)

**Comment by SirCmpwn** [comment]
Can you squash all of this when you're done?

**Comment by SethBarberee** [comment]
I tried to squash them but to no avail... I'm sorry if i'm causing a lot of trouble. I'm still new to Git and I will try to fix the problems before I try to actually make the pull request

**Comment by SethBarberee** [comment]
It says 9 days ago so I guess I squashed it? Idk

**Comment by SirCmpwn** [comment]
Do this:

    git rebase -i HEAD~18

Then replace "pick" with "squash" for all but the first commit, then save and close the file and enter a single commit message for this whole change. Then:

    git push -f

**Comment by SirCmpwn** [comment]
Whoops, you got one commit too many in the squash. This can't be merged like that. Can you just grab the relevant files and make a new commit on a new branch and open a new pull request?

**Comment by SethBarberee** [comment]
Yeah, I've been busy all week and forgot to do that. Thx!

**Comment by SethBarberee** [comment]
So I force-pushed this so now it's one commit. This should work now, I hope.

**Comment by SirCmpwn** [comment]
Looks great. Nice work!

**Pull request merged**
