### PR TITLE
Notification area support

### PR DESCRIPTION
**Pull request by sardemff7**
There’s a little cleanup/preparation commit in there, nothing mandatory, I can drop it if wanted.

This is the implementation of [this Wayland interface](https://github.com/sardemff7/wayland-notification-area/blob/master/protocol/notification-area-unstable-v2.xml) for Sway, using an helper library.
The library can be found [here](https://github.com/sardemff7/wayland-notification-area/tree/master/wlc-notification-area) (with the plugins for Weston and Orbment, implementing the compositor side) and a client implementation [here](https://github.com/sardemff7/eventd/blob/master/plugins/nd/src/backend-wayland.c).

To make it perfectly clear:
* this PR doesn’t add a D-Bus dependency to Sway;
* the notifications are drawn by an external process (“notification daemon”), as it happened in X11 with i3;
* this Wayland interface provides an area and a way to place surfaces in it, nothing more.

As of other DEs, GNOME implements the org.freedesktop.Notifications D-Bus interface [in GNOME-Shell directly](https://git.gnome.org/browse/gnome-shell/tree/js/ui/notificationDaemon.js), so they do not need any Wayland protocol to interface with a notification daemon. The [same goes for Enligthenment](https://git.enlightenment.org/core/enlightenment.git/tree/src/bin/e_notification.c).
In KDE, they [forward the D-Bus interface](https://quickgit.kde.org/?p=plasma-workspace.git&a=tree&hb=80bdf99d7b9cc90afc2b32f086ca151cc7829fe6&h=b9a6af02e36df07fff534339c20a2afd86521ffb&f=dataengines%2Fnotifications) to their Knotify system. I did not find any Wayland interface specific to notifications.

Currently, the only client I am aware of is eventd, because I designed and wrote this Wayland interface and all the related code. I doubt any other notification daemon will ever port to it, but there’s always hope.

I’m not entirely settled on the static/dynamic choice, because with a dynamic library, we could update the protocol without rebuilding Sway…
That won’t change anything in Sway, just needing a rebuild if I decide to go the dynamic way.

### CODE REVIEW

**Comment by sardemff7** [comment]
My clone was a bit out of date (failed fetch) so now, this PR is correctly based on current master.

**Comment by sardemff7** [comment]
Updated the PR with some information.

**Comment by sardemff7** [comment]
Updated again for clarity, added the link to the interface definition.

**Comment by SirCmpwn** [comment]
I'm reviewing this from several angles. 1 - do we even want this feature, 2 - how best to integrate it, and 3 - how to deal with more niche protocol extensions in general landing in Sway.

* I'd rather implement this directly in Sway rather than depend on a static library.
* Some configuration options should be given to the user to make it so they can enable/disable notifications entirely and control their position on-screen or which outputs they're constrained to.
* Another option to enable/disable notifications when the screen is locked would be nice.

If we're going to implement this code directly in sway, then I would like to see the protocol extensions refactored in general. I would establish a directory for extension implementations (rather than extensions.c like we currently have) and give each protocol its own C file concerned with implementing that protocol. This'll help for adding more protocols in the future like KWin's output configuration protocol.

I would also like to establish a man page for programmers (perhaps in section 7) that lists the protocol extensions sway supports with links to their XML files.

Tangentally, does anyone have an opinion on Sway supporting plugins via dynamic linking to implement protocol extensions? I wanted to avoid plugins but I'm not sure the monolithic nature of Wayland compositors is going to allow for that.

**Comment by sardemff7** [comment]
I am all for plugins and will happily implement that interface as a plugin if Sway goes that way.

Concerning the configuration, it all happens in the notification daemon, just like it did in X11.
The only part left to the compositor is to select the output.

To disable notifications while locked, currently, you just need to call `wlc_notification_area_set_output(na, 0)`.

If you want to put all the configuration and placement in Sway, it is up to you.
*My* notification daemon has complex placement options, possibly based on notification content, so I cannot delegate all that to the compositor.

**Comment by SirCmpwn** [comment]
I wasn't suggesting that all the configuration would be done here, but perhaps that sway could override some things and make some of these wayland functions no-ops for example. But I'm fine with leaving most of it in the daemon.

**Comment by progandy** [comment]
Why is a specific notification protocol needed? I rather think that a generic approach is more useful. It should be possible to set the role of a surface (isn't that already implemented?), get a working area (maybe depending on the role), and simply create notifications as subsurfaces.

**Comment by sardemff7** [comment]
@SirCmpwn
Output choice is already up to the compositor and disabling notifications is as simple as sending a `0,0`-sized area (since putting even 1 pixel of a notification outside the area is an error, although for my first draft I’m not sure I did that yet).
Forcing placement will just mess up with the daemon stuff, or you will need really complex heuristic to guess what was the intention.
You can limit the work area to one side of the screen or a corner, the daemon *has* to deal with it, I said already. Of course you cannot use this PR for that as the work is done in the helper lib so you cannot properly override it now.

@progandy
Having one interface per special role makes it possible to limit to one client for each of them.
If you make a generic interface, but you still want a role and per-role rules, it doesn’t give you anything.
Implementing Wayland interfaces is cheap, and we do not want all-in-one interfaces where it doesn’t make sense, by design.

**Comment by SirCmpwn** [comment]
Let's set aside the question of plugins for now. I'll merge this if:

1. It doesn't depend on a static library
2. It includes splitting up the server side implementation of each extension into seperate files

**Comment by SirCmpwn** [comment]
Let's set aside the question of plugins for now. I'll merge this if:

1. It doesn't depend on a static library
2. It includes splitting up the server side implementation of each extension into seperate files

**Comment by SirCmpwn** [comment]
Let's set aside the question of plugins for now. I'll merge this if:

1. It doesn't depend on a static library
2. It includes splitting up the server side implementation of each extension into seperate files

**Comment by SirCmpwn** [comment]
Let's set aside the question of plugins for now. I'll merge this if:

1. It doesn't depend on a static library
2. It includes splitting up the server side implementation of each extension into seperate files

**Comment by SirCmpwn** [comment]
Let's set aside the question of plugins for now. I'll merge this if:

1. It doesn't depend on a static library
2. It includes splitting up the server side implementation of each extension into seperate files

**Comment by sardemff7** [comment]
I designed my code to share the same wlc-based implementation between Orbment and Sway, to make it trivial to support both with minimal changes. Now you are basically asking to duplicate my code in Sway for the sake of having everything in Sway. I understand, but I won’t do it.

1. Do not consider this a library, just consider it implementation in a separate file in a separate project so you can share the implementation with Orbment. If it’s not ok with you, no problem, but I won’t  take such maintenance burden.
2. I had requests to support Sway, it was trivial (because I designed the code specifically for that), so I did it. But I don’t use Sway, so I won’t hack it more.

If anyone wants to do it, it’s not hard, and everything is MIT-licenced. As long as I am not the one who will have to maintain it, I’m fine.

Thanks for your time.

**Comment by sardemff7** [comment]
Ping @vially, @onny, @SethBarberee, and @quartz55 if one of you wants to maintain that.

**Comment by SethBarberee** [comment]
I would be interested. However, what work would be required to make this comply to what @SirCmpwn has described?

**Comment by sardemff7** [comment]
@SethBarberee

I just did the preliminary work and pushed it.
Here are the remaining things to do, as follow-up commits:

1. Probably rename some stuff, maybe restyle the code too
2. Split other extensions from `extensions.c` to their own files

**Comment by progandy** [comment]
Maybe it would be possible to import the files as a subtree? I guess that might satisfy both requirements "no external static libraries" and "easier support with code-sharing". People using the source without sending changes to the extension don't have to knwo about the subtree it either unlike a submodule.

**Comment by SirCmpwn** [comment]
Subtree sounds like a reasonable solution, ish.

**Comment by sardemff7** [comment]
Feel free to do anything you want, as long as you keep my authorship on the two commits of this PR. (Of course if you use subtree to import the file, you can ditch said file from my import commit.)

Good luck :-)

**Comment by sardemff7** [comment]
`wayland-notification-area` is no more, now there are `wayland-wall` (the protocols), `weston-wall` (Weston plugins for these protocols) and `orbment-wall` (Orbment plugins with, when reliable, a split of the wlc-shareable code to a specific file).

**Pull request closed without merging**
