### PR TITLE
Add --help to print usage

### PR DESCRIPTION
**Pull request by christophgysin**

### CODE REVIEW

**Comment by SirCmpwn** [comment]
If we're going to do it on `sway`, we should do it for `swaymsg` and `swaygrab` too.

**Comment by christophgysin** [comment]
Agreed. Do you want it in the same PR?

**Comment by SirCmpwn** [comment]
That'd be nice, yes.

**Comment by christophgysin** [comment]
Is there anything else missing to get this merged?

**Comment by SirCmpwn** [comment]
I don't get emailed when you push new commits - you've got to bump the thread (with a comment) for me to realize that it's updated and should be reviewed again. Thanks!

**Pull request merged**
