### PR TITLE
Added in workspace next/prev and workspace output_next/prev

### PR DESCRIPTION
**Pull request by Luminarys**

### CODE REVIEW

**Comment by SirCmpwn** [comment]
workspace next_on_output soon?

**Comment by Luminarys** [comment]
Oops, output_next/prev were supposed to be next_on_output.

**Comment by SirCmpwn** [comment]
Oh, I should have caught that. Whoops. Will you fix it or should I?

**Comment by Luminarys** [comment]
Yea, I'll handle it.

**Pull request merged**
