### PR TITLE
improve endianess handeling

### PR DESCRIPTION
**Pull request by fluxchief**

### CODE REVIEW

**Comment by SirCmpwn** [comment]
Hmm, on second thought, after more research, I'd rather not use htole32. It's nonstandard and not portable. Can we just fix the big endian path for the original strategy?

**Comment by mikkeloscar** [comment]
I'm afraid to get this wrong again, but I'm pretty sure the correct version is:

```
 cairo_set_source_rgba(cairo,
                                (color >> (2*8) & 0xFF) / 255.0,
                                (color >> (1*8) & 0xFF) / 255.0,
                                (color >> (0*8) & 0xFF) / 255.0,
                                (color >> (3*8) & 0xFF) / 255.0);
```

**Comment by fluxchief** [comment]
@SirCmpwn htonl would be POSIX, does this sound better?
@mikkeloscar I tried it out I guess and it looked right to me, but I can double check it

**Comment by SirCmpwn** [comment]
Yes, that would be acceptable.

**Comment by mikkeloscar** [comment]
+1 for htonl

**Comment by fluxchief** [comment]
I switched to htonl, colors look good to me, please have another look & merge

**Comment by mikkeloscar** [comment]
LGTM.

**Pull request merged**
