### PR TITLE
swaylock: option parsing

### PR DESCRIPTION
**Pull request by christophgysin**

### CODE REVIEW

**Comment by mikkeloscar** [comment]
LGTM, but since it changes the arguments I will let @SirCmpwn have a look :)

**Comment by SirCmpwn** [comment]
We should implement the same command line as i3lock.

**Comment by christophgysin** [comment]
That was the intention. i3lock does not support --scaling <mode>. But I added --tiling,  to be commandline compatible to i3lock.

Is there something I should change to get this merged?

**Comment by SirCmpwn** [comment]
Sorry, I misunderstood @mikkeloscar's comment. This looks fine.

**Pull request merged**
