### PR TITLE
commands: Learn 'focus output <direction|name>'

### PR DESCRIPTION
**Pull request by sce**
Replicates i3 functionality. This is the first part of pull request #205 , and it works properly.
(+ The fix for moving floating windows to other workspaces.)

Please review, comments are welcomed.

### CODE REVIEW

**Comment by SirCmpwn** [comment]
So does this make #205 obsolete?

**Comment by sce** [comment]
#205 still contains more functionality, so I'm not done with that yet (I'll update it appropriately).

**Comment by SirCmpwn** [comment]
So what do you want me to do with each of these PRs?

**Comment by sce** [comment]
Oh, sorry for being unclear.

#205 actually contains three separate functionalities. This pull request is the first one from #205 , it's unrelated to the other two, has no issues, and therefore can be merged.

Once this is merged I'll update (force push) #205 to only contain the unmerged code (the remaining two functionalities), and I'll continue the discussion there. Later, I'll clean up the remaining code in #205 and ask you for a formal review/merge of that pull request.

**Comment by SirCmpwn** [comment]
Got it, thanks. Reviewing this now.

**Comment by sce** [comment]
Excellent, thanks!

**Pull request merged**
