### PR TITLE
Detecting Raspberry PIs and advising to use correct video mode

### PR DESCRIPTION
**Pull request by refacto**
This is a pull request meant to help with people experiencing the problems detailed in #143 by detecting if sway is being run on a Raspberry Pi and if the vc4 module is loaded. If the module isn't loaded, it's safe to assume the Pi isn't in the correct video mode, and the error message contains instructions to boot with the correct video mode.

### CODE REVIEW

**Comment by refacto** [comment]
I can add some explanation in the FAQ or wiki if there's demand.

**Comment by SirCmpwn** [comment]
Thanks!

**Comment by refacto** [comment]
Just a quick question -- Anything I could do to close the bounty for ARM support? ARM support is essentially here now.

**Comment by SirCmpwn** [comment]
Gotta wait until it ships in a stable version and has a couple weeks of user testing. Need an incentive for you to stick around and help fix bugs!

**Pull request merged**
