### PR TITLE
input_state.ch, and command conflicts resolved

### PR DESCRIPTION
**Pull request by taiyu-len**
created an input_state.[ch] which we use to keep track of pointer/ and key presses.
and used the functions where they should in handlers.c

fixed bindsym conflicts, by sorting them from longest bindsym to shortest,
and having the handle_key return when it matches a bindsym.
this is how it works on i3, for example winkey+shift+space -> toggle floating, winkey+space -> focus toggle, 
works as it should.

added a `get_swayc_in_direction(swayc_t *)` which can be used to get the container in whatever direction, returns null if there is no such container.

### CODE REVIEW

**Comment by SirCmpwn** [comment]
This reverts some of the choices I made last night, namely:

* Using an enum instead of a define for the buffer size (wtf dude)
* Using memmove instead of just fragmenting the buffer

Put those changes back in and it's okay to merge.

**Comment by taiyu-len** [comment]
done. i also fixed some problems in the man pages.

**Comment by SirCmpwn** [comment]
/home/sircmpwn/sources/sway/sway/handlers.c: In function ‘handle_key’:
    /home/sircmpwn/sources/sway/sway/handlers.c:319:7: warning: variable ‘mod’ set but not used [-Wunused-but-set-variable]
      bool mod = false;
           ^

**Comment by SirCmpwn** [comment]
Looks good, fix the warning and I'll merge.

**Comment by taiyu-len** [comment]
thats from whatever changes you were working on last night, i just left it alone.
ill just comment it out, while you can do whatever you were doing with it later.

**Comment by SirCmpwn** [comment]
Whoops, didn't realize I had introduced it. Don't worry about it.

**Pull request merged**
