### PR TITLE
Translate README.md to Greek / Μετάφραση του README.md στα Ελληνικά

### PR DESCRIPTION
**Pull request by kon14**
I've only translated the README for now, but plan on doing the rest of the files in the following days.

The localized README mentions it's still incomplete and points to related issue thread for localization guidelines. I also updated the main README with links to the Greek, French and Spanish versions (which are yet to be merged, but I imagine you wouldn't mind merging these soon anyway?)

### CODE REVIEW

**Comment by SirCmpwn** [comment]
>In the README, clarify the situation for speakers of that language who wish to get support. If you can volunteer to hang out in IRC and triage GitHub issues, mention your username and timezone.

Also, can you move translation status up and make it the first heading after the screenshot?

**Comment by kon14** [comment]
I'll update this to reflect upon the above. Will also add a reply to the localization thread.

**Comment by SirCmpwn** [comment]
This still needs to clarify how to get support in Greek - I clarified in the guidelines the language to use.

**Comment by SirCmpwn** [comment]
Ευχαριστώ!

**Pull request merged**
