### PR TITLE
Fix #868

### LINKED ISSUE #868: Segmentation fault when switching from empty workspace
Sway segfaults when switching from workspace with no windows to another workspace.

```
Core was generated by `sway -dV'.
Program terminated with signal SIGSEGV, Segmentation fault.
#0  0x000055f2567476bb in update_container_border (container=0x41) at /var/tmp/portage/dev-libs/sway-9999/work/sway-9999/sway/border.c:418
418     /var/tmp/portage/dev-libs/sway-9999/work/sway-9999/sway/border.c: No such file or directory.
(gdb) bt full
#0  0x000055f2567476bb in update_container_border (container=0x41) at /var/tmp/portage/dev-libs/sway-9999/work/sway-9999/sway/border.c:418
No locals.
#1  0x000055f2567476fe in update_container_border (container=0x55f257931b00) at /var/tmp/portage/dev-libs/sway-9999/work/sway-9999/sway/border.c:423
        i = 0
#2  0x000055f256734d92 in set_focused_container (c=0x55f25793ca40) at /var/tmp/portage/dev-libs/sway-9999/work/sway-9999/sway/focus.c:142
        parent = 0x55f25793ca40
        active_ws = 0x55f257931b00
        active_ws_child_count = 0
        workspace = 0x55f25793ca40
        focused = 0x55f257931b00
        p = 0x55f256956fc0 <root_container>
#3  0x000055f256745a9a in workspace_switch (workspace=0x55f25793ca40) at /var/tmp/portage/dev-libs/sway-9999/work/sway-9999/sway/workspace.c:307
        active_ws = 0x55f257931b00
        output = 0x0
#4  0x000055f256727281 in cmd_workspace (argc=1, argv=0x55f2574027e8) at /var/tmp/portage/dev-libs/sway-9999/work/sway-9999/sway/commands.c:2584
        ws = 0x55f25793ca40
        old_output = 0x55f2578f36e0
        new_output = 0x0
        error = 0x0
#5  0x000055f25672ad01 in handle_command (_exec=0x55f2573a2f60 "workspace 2") at /var/tmp/portage/dev-libs/sway-9999/work/sway-9999/sway/commands.c:3603
        argc = 2
        argv = 0x55f2574027e0
        handler = 0x55f2569563a0 <handlers+800>
        res = 0x7f0f9d399d77 <strcasecmp+119>
        results = 0x0
        exec = 0x55f257935140 "workspace 2"
        head = 0x0
        cmdlist = 0x0
        cmd = 0x55f257935140 "workspace 2"
        criteria = 0x0
#6  0x000055f256736e1e in handle_binding_command (binding=0x55f2573a2f20) at /var/tmp/portage/dev-libs/sway-9999/work/sway-9999/sway/handlers.c:574
        binding_copy = 0x55f2573a2f20
        reload = false
        res = 0x19197b0d0
#7  0x000055f256736f63 in handle_bindsym (binding=0x55f2573a2f20, keysym=50, keycode=3) at /var/tmp/portage/dev-libs/sway-9999/work/sway-9999/sway/handlers.c:599
        key = 0x55f2573a3580
        i = 0
[...]
```
Core Dump: [core.zip](https://github.com/SirCmpwn/sway/files/428488/core.zip)

### PR DESCRIPTION
**Pull request by kobezda**
Fixes #868

### CODE REVIEW

**Comment by SirCmpwn** [comment]
This is reverting a commit, right? Which one?

**Comment by kobezda** [comment]
Yes, it reverts a line from 81eb9ea12c322b8b966779ec2e170820e06c5eb7

**Comment by SirCmpwn** [comment]
Paging @acrisci for comment

**Comment by acrisci** [comment]
@kobezda can you provide detailed steps to reproduce the issue?

**Comment by kobezda** [comment]
@acrisci Steps to reproduce:
1. Install sway from git on a gentoo hardened installation
2. run sway
3. Without opening any windows, change workspace
I'm not sure how much more detailed I can get, it happens every time on my system. 
System details are in the issue, here's full emerge --info output: 
[emerge_info.txt](https://github.com/SirCmpwn/sway/files/465631/emerge_info.txt)

**Comment by acrisci** [comment]
I can't reproduce this issue but I'm on Fedora. I'll have to dig a little deeper then. Can anyone else reproduce this issue?

**Comment by kobezda** [comment]
I haven't heard of anyone else having this problem yet. I'm suspecting it's because of some hardening feature in my toolchain... See https://wiki.gentoo.org/wiki/Hardened/Toolchain - most look like they can be enabled on Fedora via compile-time gcc flags.

**Comment by kobezda** [comment]
Can anyone try to reproduce with -fPIE -fstack-protector? Here's a patch for CMakeLists.txt: 
[cflags-hardened.patch.txt](https://github.com/SirCmpwn/sway/files/465660/cflags-hardened.patch.txt)

**Comment by acrisci** [comment]
I can indeed reproduce the issue only with that patch applied. I give this priority and find the root cause of the problem tomorrow.

**Comment by kobezda** [comment]
Any progress on this, @acrisci?

**Comment by zandrmartin** [comment]
For whatever it's worth I am able to reproduce the problem with the CMake patch and the fix by reverting that line. I tried tracing through all the focus logic but the root cause of this problem didn't jump out at me.

**Pull request closed without merging**
