### PR TITLE
Switch to adjacent output when hitting output edge.

### PR DESCRIPTION
**Pull request by sce**
A much simpler implementation of #198 .

### CODE REVIEW

**Comment by SirCmpwn** [comment]
Nice. Will merge once build passes.

**Comment by SirCmpwn** [comment]
Actually, can you make this behaviour toggle with a config flag?

**Comment by sce** [comment]
Sure, what do you want to call it?

**Comment by SirCmpwn** [comment]
`seamless_mouse [on|off]` or something?

**Comment by SirCmpwn** [comment]
:tada:

**Pull request merged**
