### PR TITLE
[RFC] Add tests

### PR DESCRIPTION
**Pull request by SirCmpwn**
Tests are enabled by default if you have [cmocka](https://cmocka.org/) installed. Run `make && make check` to run the test suite. You can enable coverage reporting by invoking cmake with `-Denable-coverage=YES` and having lcov and gcov installed. A coverage report is output to `coverage/index.html`.

### CODE REVIEW

**Comment by mikkeloscar** [comment]
Awesome :+1:

**Comment by SirCmpwn** [comment]
Ran into some bullshit. Not moving forward with cmocka.

**Comment by AbstractBeliefs** [comment]
Would you mind a brief explanation of the bullshit you ran into for those who 1) are considering different test frameworks and 2) a little insight into what you're looking for and looking to avoid for tests in sway?

**Comment by SirCmpwn** [comment]
A number of things. First, I ran into issues with bus errors and segfaults when accessing shared pointers between tests and tested code. I ran into this when I started to write tests for commands, which need the config global to be usable. For that to be usable I need to set up config defaults and clean up after the test. The second issue is that when digging into cmocka to find out more, I found it to be implemented in one big C file. This confirmed my suspicions that it wasn't very good, which I thought from the start based on the poor documentation and less-than-ideal set of assertions.

**Pull request closed without merging**
