### PR TITLE
Translate README to German / Übersetzung des READMEs ins Deutsche

### PR DESCRIPTION
**Pull request by refacto**

### CODE REVIEW

**Comment by refacto** [comment]
Whoops, I didn't see that someone had already created a PR for translating to German. I'm sorry!

**Comment by SirCmpwn** [comment]
No worries. Maybe you can read over their PR and leave some feedback?

**Comment by refacto** [comment]
Have suggested some changes,

**Comment by SirCmpwn** [comment]
Danke!

**Pull request closed without merging**
