### PR TITLE
cmd_output: Merge instead of replace output config

### PR DESCRIPTION
**Pull request by christophgysin**

### CODE REVIEW

**Comment by SirCmpwn** [comment]
Looks good. Remove that TODO, though, that doesn't sound like a config option worth having.

**Comment by christophgysin** [comment]
What about sending a command at runtime to enable/disable an output?

**Comment by SirCmpwn** [comment]
I thought that was already supported? Does this break that?

**Comment by christophgysin** [comment]
There is currently no way to know if the `enabled` flag was set, and should be merged.

**Comment by SirCmpwn** [comment]
I see what you mean now. We could change it to an int, -1 for unset (enabled), 0 for disabled, 1 for enabled?

**Comment by SirCmpwn** [comment]
I'm pretty sure not being able to disable outputs at runtime will break the workflow of that one guy.

**Comment by christophgysin** [comment]
I can turn it into an integer, and use -1 for unset, 0 for disabled, and 1 for enabled...

**Comment by christophgysin** [comment]
You beat me to it :)

**Comment by christophgysin** [comment]
How about this?

**Comment by SirCmpwn** [comment]
Does the code need to be changed for when an output is added to make sure it's not immediately disabled by default?

**Comment by christophgysin** [comment]
-1 is still true. Or did I miss something?

**Comment by SirCmpwn** [comment]
Oh, I thought -1 was false.

**Pull request merged**
