### PR TITLE
[WIP] Swaybar refactor

### PR DESCRIPTION
**Pull request by mikkeloscar**
Here we go.

Initial effort to refactor swaybar into multiple files.

##### What does this do?:
* [x] Move render functions to `render.{h,c}`
* [x] Move command_status i3bar json handling to `status_line.{h,c}`
* [x] Move ipc stuff to `ipc.{h,c}`
* [x] Move global `main.c` variables to global `bar struct` (`bar.{h,c}`).
* [x] Refactor `status_command` spawn/teardown.

Right now the `bar` is global to `main.c` and is passed to the sub functions, but it could also be made global for all files if that is preferred.

### CODE REVIEW

**Comment by SirCmpwn** [comment]
Figured if I left this alone for long enough someone else would do it :wink: 

Should I wait for those check boxes to be checked before review/merge?

**Comment by mikkeloscar** [comment]
I would love a general review, just to see if you like this direction or not before I continue further. But don't merge until those are ticked off :)

**Comment by SirCmpwn** [comment]
Just took a look, it's all good. I like where this is heading.

**Comment by mikkeloscar** [comment]
This is ready for review/test/merge.

**Comment by crondog** [comment]
Looks ok and it didn't crash when I ran it :+1:

**Comment by SirCmpwn** [comment]
Nice!

**Pull request merged**
