### PR TITLE
Refactor preprocessor logic out of _sway_log()

### PR DESCRIPTION
**Pull request by 1ace**
This removes most preprocessor logic, leaving it only it the header, which I find cleaner.
I won't be offended if you prefer the old code and don't want my patch, so feel free to just tell me so :stuck_out_tongue_winking_eye:

### CODE REVIEW

**Comment by SirCmpwn** [comment]
:+1:, but sync this with master and I'll merge it once tests pass

**Comment by 1ace** [comment]
Sorry, just tried to use github's "update branch" functionnality, and it created a merge. Give me a second and I'll do a proper rebase instead.

**Comment by SirCmpwn** [comment]
Sorry, you'll have to sync it up again.

**Comment by 1ace** [comment]
Done :]

There couldn't possibly be any merge conflict here. Is GitHub requesting a rebase/merge every time the file is modified regardless of conflicts? That's going to be a pain :/

**Comment by SirCmpwn** [comment]
The issue is that when your branch isn't lined up with the master branch, the builds won't be running against the codebase that master would *become* if this was merged, but rather an older version of it.

**Comment by 1ace** [comment]
The build *could* run against master + the merged PR, as that will be the real result that the build is meant to test for :P
Regardless, this is probably not something you can change, so I might as well just accept it :]

**Pull request merged**
