### PR TITLE
Translate README to russian 

### PR DESCRIPTION
**Pull request by DarkReef**
Well, I just translated the readme file on russian. The translation looks clean, but it's possible that I missed something, so...

### CODE REVIEW

**Comment by SirCmpwn** [comment]
Thank you! You are missing a few things, though, please read the guidelines (https://github.com/SirCmpwn/sway/issues/1318).

**Comment by SirCmpwn** [comment]
Thanks! I don't actually see you in the IRC channel - can you actually commit to providing support there?

**Comment by DarkReef** [comment]
Well, I'm about to join the channel. And yes, I can provide support here.

**Comment by SirCmpwn** [comment]
Great! One more change - add a link to your README in the English README.md file.

**Comment by DarkReef** [comment]
Done

**Comment by SirCmpwn** [comment]
Спасибо!

**Pull request merged**
