### PR TITLE
Implement bar option: colors {}

### PR DESCRIPTION
**Pull request by mikkeloscar**
This only supports the color format `#rrggbb`. I see that the colors are defined with an alpha channel in `swaybar/main.c` should I extend it to also allow the format `#rrggbbaa`?

Also note that I have remove the color `foreground` I don't know if this was just an error or you intended to provide an extra color not available in i3?

### CODE REVIEW

**Comment by SirCmpwn** [comment]
Nice work. The foreground thing was a mistake. Can you extend this to support rgba?

**Comment by mikkeloscar** [comment]
I will add rgba support!

**Comment by mikkeloscar** [comment]
rgba support added. It is now possible to define the color as `#rrggbb` or `#rrggbbaa`.

**Comment by SirCmpwn** [comment]
Coolio, thanks!

**Pull request merged**
