### PR TITLE
swaybar: fix logging

### PR DESCRIPTION
**Pull request by crondog**
Optionally turn on debugging in swaybar. I acidentally introduced
persistent logging in a previous commit

### CODE REVIEW

**Comment by mikkeloscar** [comment]
You should also add info about the debug option in the man page.

**Comment by crondog** [comment]
There is no swaybar man page. There is an issue for it though https://github.com/SirCmpwn/sway/issues/375

**Comment by mikkeloscar** [comment]
I must have been thinking about one of the other sway* binaries. But then it LGTM.

**Comment by crondog** [comment]
Ah I think I know what you mean. A swaybar.1,txt ie the binary man page. That doesn't exist either

```
find . -name "sway*.txt"
./swaymsg/swaymsg.1.txt
./sway/sway.5.txt
./sway/sway.1.txt
./swaygrab/swaygrab.1.txt
```

**Pull request merged**
