### PR TITLE
Updated readme dependency list

### PR DESCRIPTION
**Pull request by minus7**

### CODE REVIEW

**Comment by SirCmpwn** [comment]
oneliner for arch is `yaourt -S sway-git`.

**Comment by FSMaxB** [comment]
There is no oneliner for arch because arch has no default AUR-Helper.

**Comment by SirCmpwn** [comment]
lol, who doesn't have one installed

**Comment by SirCmpwn** [comment]
In any case, an arch oneliner is not necessary:

https://github.com/SirCmpwn/sway#from-packages

**Comment by FSMaxB** [comment]
All I wanted to say is that there is no oneline that works for everyone because different people use different AUR helpers.

**Comment by minus7** [comment]
It's listed under `compile from source` and just lists sway's deps, but i guess you could just install sway from the package and thus have the deps too. it was meant as a simple/quick way to just install the deps.

**Comment by SirCmpwn** [comment]
Well, can you take it out?

**Pull request merged**
