### PR TITLE
Implement bar option: font <font>

### PR DESCRIPTION
**Pull request by mikkeloscar**

### CODE REVIEW

**Comment by SirCmpwn** [comment]
Can you leave a warning if they try to use a non-pango font?

**Comment by mikkeloscar** [comment]
Will a pango font always be defined as `pango:some font name` ?

**Comment by mikkeloscar** [comment]
And the warning should say that a non-pango font isn't supported, right?

**Comment by SirCmpwn** [comment]
Yes

**Comment by mikkeloscar** [comment]
Updated with `pango:` check and warning.

**Pull request merged**
