### PR TITLE
Bar confing subcommands

### PR DESCRIPTION
**Pull request by mikkeloscar**
Some more bar config options implemented.
* `positon <top|bottom|left|right>`
* `strip_workspace_numbers <yes|no>`
* `tray_output` (message about it not being supported)

### CODE REVIEW

**Comment by SirCmpwn** [comment]
Nice.

**Comment by StephenBrown2** [comment]
Just another silly question, but why is tray_output not supported, but tray_padding is a thing?

I hope it's not supported *yet* because it's not implemented yet, in which case the message should be different. However, I presume it's partially because wayland is not X, but I don't know why.

**Comment by mikkeloscar** [comment]
I think `tray_padding` was implemented before I realized that a systray wouldn't be supported by wayland in the current state (could be implemented eventually).

**Comment by SirCmpwn** [comment]
Tray icons aren't a thing on Wayland yet. I was planning on making up some protocol extensions for it and then submitting it to the major toolkit vendors to review/ignore.

**Comment by StephenBrown2** [comment]
I see. As I suspected, "because wayland is not X". ;-)

So in order for system tray icons to work in wayland, there has to be something at the wlc layer, or lower, I presume.

*digs further into "what is a systray icon?"*

Oh, wow, yeah, that's some interesting X stuff there.
> "Having decided that we can't drop support just yet, it seems unlikely we can drop it in a few months when we switch to Wayland. So we need to consider how to make that work there. Embedding an X window inside a wayland window isn't going to work."

^- http://blog.davidedmundson.co.uk/blog/xembed_back


> "The system tray is an X client which owns a special manager selection on a given screen and provides container windows."

^- http://standards.freedesktop.org/systemtray-spec/systemtray-spec-latest.html


> "XEmbed is a protocol that uses basic X mechanisms such as client messages and reparenting windows to provide embedding of a control from one application into another application."

^- http://standards.freedesktop.org/xembed-spec/xembed-spec-latest.html

When the day comes that you decide to take on that task, I would ask that you consider supporting app indicators as well? (Cinnamon 2.8 just recently added support, Ubuntu's had them for a while, and since Ubuntu is the biggest, many applications are now supporting them)
http://www.notmart.org/misc/statusnotifieritem/
https://awesome.naquadah.org/bugs/index.php?do=details&task_id=1034
And holy cow the links and information: https://github.com/picoe/Eto/issues/291

(A new issue should likely be spawned for systray stuff by itself, methinks)

**Pull request merged**
