### PR TITLE
Setenv command

### PR DESCRIPTION
**Pull request by thuck**
This makes sway to be able to set environment variables from the configuration file.
The basic syntax follows the same concept as the set command.
The current behavior is to update the var if it's already configured somewhere.

### CODE REVIEW

**Comment by SirCmpwn** [comment]
:-1: 

Why not just, you know, set the environment variables before starting up sway?

**Comment by thuck** [comment]
You could set on your .profile, and you could set it on a wrapper for sway.
A wrapper for this case looks bad, and also I don't think would play very nice with a DM, even more when sway starts to be included in the major distros.
Another aspect is that with this you can have specific environments variables depending where you are running sway; using the include with hostname.

I use a similar configuration with awesome, since I need some env vars specific for it, but I don't need it for other things; but if you think this is not a good approach you can close it, no problem :)

**Comment by SirCmpwn** [comment]
>Another aspect is that with this you can have specific environments variables depending where you are running sway; using the include with hostname.

That still works without this feature, just make your wrapper check the hostname and set the environment accordingly.

**Comment by thuck** [comment]
Sure; but you can use a wrapper basically for doing anything, including to simulate the include.
I understand that there is different possibilities to handle this, but I think this is simpler than the other options.
If you prefer you can keep this open, and check if people would like to have it included or not.

**Comment by jplatte** [comment]
FWIW, I'm lurking here all the time to see when it might become usable for me, and I personally have never had a need for DE-specific environment variables, nor do I see an advantage in having environment variables in the sway config file instead of setting them whereever you start sway from or creating a wrapper if you don't start sway from a shell script yet.

**Comment by SirCmpwn** [comment]
Going to close this for now. May consider the feature later.

**Pull request closed without merging**
