### PR TITLE
FreeBSD fixes

### PR DESCRIPTION
**Pull request by johalun**
Increase _POSIX_SOURCE value for localtime_r access.
Increase _XOPEN_SOURCE value for lstat() and various printf() functions access.
Conditionally link to libcap (only on Linux).
Possibly some trailing whitespace fixes (automatic).

### CODE REVIEW

**Comment by SirCmpwn** [comment]
Please don't increase _XOPEN_SOURCE globally, but rather only in files where the newer functions are required.

**Comment by johalun** [comment]
After fixing 6-7 files manually I gave up and replace everywhere. I'll give it another shot.

**Comment by johalun** [comment]
Fixed.

**Comment by SirCmpwn** [comment]
Thanks!

**Pull request merged**
