### PR TITLE
Configure outputs during reload 

### PR DESCRIPTION
**Pull request by sce**
config: Apply output config also during config reload.

My biggest patch so far, this code allows sway to apply changes in outputs config after config reload.

The position data isn't used (so far), but the resolution of the different outputs can now be changed on the fly by simply reloading the config. Everything seems to be working nicely. Please review.

### CODE REVIEW

**Comment by SirCmpwn** [comment]
Can an output be resized via i3-msg on the fly?

**Comment by sce** [comment]
For some reason it doesn't work, the command just returns "failed". It's supposed to work, but I haven't looked into why yet. I can look into it now.

**Comment by SirCmpwn** [comment]
I'd prefer to know why that doesn't work before this is merged.

**Comment by sce** [comment]
I don't know why that check was there, but changing resolution works on the fly via i3-msg now.

**Comment by sce** [comment]
(That config reload check originated in commit 0bea2e2122bd573d1f9dc68b5a990c8f2ad3f3f0 .)

**Comment by SirCmpwn** [comment]
Cool. I'll merge once travis is done with it.

**Comment by sce** [comment]
Excellent, thanks!

**Comment by SirCmpwn** [comment]
No, thank you for all the excellent pull requests :)

**Comment by sce** [comment]
My pleasure, it's an excellent way for me to learn C. ;-)

**Pull request merged**
