### PR TITLE
Respect xdg-positioner offset, anchor edges and gravity

### PR DESCRIPTION
**Pull request by Hummer12007**
Made possible by Cloudef/wlc#234.
Epiphany window size is still wrong though (might be a gtk issue).

### CODE REVIEW

**Comment by SirCmpwn** [comment]
Code style

**Comment by Hummer12007** [comment]
You want me to put in a bunch of braces?

**Comment by SirCmpwn** [comment]
Yes

**Comment by SirCmpwn** [comment]
Thanks!

**Pull request merged**
