### PR TITLE
Terminate when both suid bit and filecaps are set

### PR DESCRIPTION
**Pull request by Hummer12007**
Do not merge. Yet to test it.

### CODE REVIEW

**Comment by SirCmpwn** [comment]
This good to go?

**Comment by Hummer12007** [comment]
Nope, didn't feel too well yesterday to look into it, but apparently resolve_path somehow failed.

**Comment by Hummer12007** [comment]
Ok now.

**Comment by SirCmpwn** [comment]
Thanks!

**Pull request merged**
